/**
 * functions/src/alerts/sendParentAlert.ts — the crisis-delivery server half
 * (w1 M1.2 — §8 #26/#27; donor pattern: firebase-functions-samples
 * fcm-notifications, Apache-2.0).
 *
 * CRISIS DIFFERENTIATION (§8 #27 — LOAD-BEARING, fail closed):
 *   - `self_harm` / `severe_distress` → PARENT alert: `alerts/{id}` doc +
 *     FCM push (+ EMAIL fallback when no FCM token delivers) + an
 *     unacknowledged re-escalation pass.
 *   - `abuse` / `csam` → **NO parent auto-alert** (the parent may be the
 *     abuser): NO alert doc, NO push, NO email. A `safetyReports/{id}` record
 *     is written to the ADMIN-ONLY mandated-reporter queue and the flagged
 *     transcripts are marked `legalHold:true` (TTL/purge-exempt, §2.5).
 *
 * Token TYPE routing (§8 #26): `admin.messaging().send()` accepts only real
 * FCM registration tokens — `apns`/`expo` records are skipped by the FCM leg
 * (they are the Expo-Push/APNs lane, a deploy-time binding) and the email
 * fallback covers delivery.
 */
import {
  alertDoc as alertDocPath,
  computeTtlAt,
  safetyReportDoc,
  transcriptDoc,
  type AlertSeverity,
  type CrisisType,
  type FcmTokenRecord,
  type ModerationCategory,
} from "@tiny-bubbles/shared";

import type { Clock, DbPort, EmailPort, MessagingPort } from "../ports";

/** Alerts outlive transcripts so the parent can act (longer TTL — §2.3). */
export const ALERT_RETENTION_DAYS = 90;

export interface SendParentAlertInput {
  childId: string;
  parentUid: string;
  severity: AlertSeverity;
  /** human-readable, NON-clinical */
  reason: string;
  crisisType?: CrisisType;
  categories?: ModerationCategory[];
  /** redacted turn ids for context */
  transcriptWindow: string[];
  /** COPY of the redacted window (survives the transcript TTL — §2.3) */
  pinnedTurns: { childText: string; replyText: string; atMs: number }[];
}

export interface SendParentAlertResult {
  route: "parent_alert" | "safety_report";
  alertId?: string;
  safetyReportId?: string;
  deliveredFcm: boolean;
  deliveredEmail: boolean;
}

export interface AlertIdGen {
  newId(): string;
}

export async function sendParentAlert(
  deps: { db: DbPort; messaging: MessagingPort; email: EmailPort; clock: Clock; ids: AlertIdGen },
  input: SendParentAlertInput,
): Promise<SendParentAlertResult> {
  const nowMs = deps.clock.nowMs();

  // ---- abuse/csam → the NO-parent-auto-alert lane (§8 #27) --------------
  if (input.crisisType === "abuse" || input.crisisType === "csam") {
    const safetyReportId = deps.ids.newId();
    await deps.db.setDoc(safetyReportDoc(safetyReportId), {
      id: safetyReportId,
      childId: input.childId,
      crisisType: input.crisisType,
      transcriptWindow: input.transcriptWindow,
      status: "open",
      createdAt: deps.db.tsFromMillis(nowMs),
    });
    // Preserve the evidence: mark the window's transcripts legalHold.
    for (const turnId of input.transcriptWindow) {
      try {
        await deps.db.updateDoc(transcriptDoc(input.childId, turnId), { legalHold: true });
      } catch {
        // a missing turn is not a reason to fail the report
      }
    }
    return { route: "safety_report", safetyReportId, deliveredFcm: false, deliveredEmail: false };
  }

  // ---- self_harm / severe_distress → parent alert (dual channel) --------
  const alertId = deps.ids.newId();
  const parent = await deps.db.getDoc(`users/${input.parentUid}`);
  const tokens = Array.isArray(parent?.fcmTokens) ? (parent.fcmTokens as FcmTokenRecord[]) : [];

  let deliveredFcm = false;
  for (const record of tokens) {
    if (record.type !== "fcm") continue; // §8 #26 — apns/expo ride the fallback lane
    try {
      await deps.messaging.send({
        token: record.token,
        title: "Please check in",
        body: "Your child may need support right now. Open Tiny Bubbles for details.",
        data: { alertId, childId: input.childId },
      });
      deliveredFcm = true;
    } catch {
      // dead token — keep trying the rest
    }
  }

  let deliveredEmail = false;
  const email = typeof parent?.email === "string" ? parent.email : "";
  if (!deliveredFcm && email) {
    try {
      await deps.email.send(
        email,
        "Tiny Bubbles — please check in with your child",
        "Your child may need support right now. Open the Tiny Bubbles parent app for details. " +
          "This alert was generated by the safety layer; the chat transcript is available in your dashboard.",
      );
      deliveredEmail = true;
    } catch {
      deliveredEmail = false;
    }
  }

  await deps.db.setDoc(alertDocPath(input.childId, alertId), {
    id: alertId,
    childId: input.childId,
    parentUid: input.parentUid,
    ...(input.crisisType ? { crisisType: input.crisisType } : {}),
    severity: input.severity,
    reason: input.reason,
    ...(input.categories ? { categories: input.categories } : {}),
    transcriptWindow: input.transcriptWindow,
    pinnedTurns: input.pinnedTurns.map((t) => ({
      childText: t.childText,
      replyText: t.replyText,
      at: deps.db.tsFromMillis(t.atMs),
    })),
    status: "new",
    deliveredFcm,
    deliveredEmail,
    createdAt: deps.db.tsFromMillis(nowMs),
    expiresAt: deps.db.tsFromMillis(computeTtlAt(nowMs, ALERT_RETENTION_DAYS)),
  });

  return { route: "parent_alert", alertId, deliveredFcm, deliveredEmail };
}

/** How long an alert may sit `new` before the escalation pass re-sends (§8 #26). */
export const RE_ESCALATE_AFTER_MS = 30 * 60 * 1000;

/**
 * Scheduled companion: any crisis alert still `status:"new"` after
 * RE_ESCALATE_AFTER_MS is re-sent on BOTH channels and stamped
 * `reEscalatedAt` (once). Runs from the same scheduler as ttlSweep.
 */
export async function reEscalateUnacknowledged(
  deps: { db: DbPort; messaging: MessagingPort; email: EmailPort; clock: Clock },
  nowMs: number = deps.clock.nowMs(),
): Promise<number> {
  const stale = await deps.db.queryGroup("alerts", "status", "==", "new");
  let escalated = 0;
  for (const doc of stale) {
    if (doc.data.severity !== "crisis") continue;
    if (doc.data.reEscalatedAt) continue; // once only
    const createdMs = deps.db.tsToMillis(doc.data.createdAt);
    if (createdMs === null || nowMs - createdMs < RE_ESCALATE_AFTER_MS) continue;

    const parentUid = typeof doc.data.parentUid === "string" ? doc.data.parentUid : "";
    const parent = parentUid ? await deps.db.getDoc(`users/${parentUid}`) : null;
    const tokens = Array.isArray(parent?.fcmTokens) ? (parent.fcmTokens as FcmTokenRecord[]) : [];
    let delivered = false;
    for (const record of tokens) {
      if (record.type !== "fcm") continue;
      try {
        await deps.messaging.send({
          token: record.token,
          title: "Reminder: please check in",
          body: "An earlier alert has not been opened yet.",
          data: { alertId: doc.id },
        });
        delivered = true;
      } catch {
        // keep trying
      }
    }
    const email = typeof parent?.email === "string" ? parent.email : "";
    if (email) {
      try {
        await deps.email.send(
          email,
          "Tiny Bubbles — reminder to check in",
          "An earlier safety alert has not been acknowledged yet. Please open the parent app.",
        );
        delivered = true;
      } catch {
        // fall through
      }
    }
    if (delivered) {
      await deps.db.updateDoc(doc.path, { reEscalatedAt: deps.db.tsFromMillis(nowMs) });
      escalated += 1;
    }
  }
  return escalated;
}
